class CameraBrands {
  static const List<String> brands = [
    'Adox',
    'Agfa',
    'Agifold',
    'Aires',
    'Akarelle',
    'Alps',
    'Alissa',
    'Ansco',
    'Arette',
    'Argus',
    'Asaflex',
    'Asanuma',
    'Auto Terra',
    'Aviva',
    'B.A.',
    'Balda',
    'Beirette',
    'Bronica',
    'Canon',
    'Chinon',
    'Contax',
    'Cosina',
    'Exakta',
    'Fuji',
    'Fujifilm',
    'Konica',
    'Minolta',
    'Minox',
    'Nikon',
    'Olympus',
    'Pentax',
    'Ricoh',
    'Rollei',
    'Samsung',
    'Sony',
    'Yashica',
    'Zeiss (Ikon)',

    // ... add more brands ...
  ];
}
